setwd("F:/数据及程序/chapter14/上机实验")
Data <- read.csv("./data/business_circle.csv", header = TRUE, encoding = 'utf-8')
colnames(Data) <- c("number", "x1", "x2", "x3", "x4")
attach(Data)
y1 = (x1 - min(x1)) / (max(x1) - min(x1))
y2 = (x2 - min(x2)) / (max(x2) - min(x2))
y3 = (x3 - min(x3)) / (max(x3) - min(x3))
y4 = (x4 - min(x4)) / (max(x4) - min(x4))
standardized <- data.frame(Data[, 1], y1, y2, y3, y4)
write.csv(standardized, "./tmp/standardizedData.csv", row.names = TRUE)